name: Deploy to Firebase Hosting
'on':
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      
      - name: Check Prettier formatting
        run: npm run check-format
      
      - name: Fail if formatting errors
        if: ${{ failure() }}
        run: exit 1
        
      - run: npm run prettify
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROTASKI_9 }}'
          channelId: live
          projectId: protaski-9
