name: Deploy to Firebase Hosting
'on':
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install

      - name: Save Firebase service account key
        id: auth
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > ${{ runner.temp }}/firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ runner.temp }}/firebase-key.json" >> $GITHUB_ENV

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Print environment variables
        run: printenv

      - name: Deploy to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-key.json
        run: firebase deploy --only hosting
        working-directory: ${{ github.workspace }}
